name: creator-shorts
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pillow
  - moviepy
  - opencv
  - gradio
  - pytz
  - ffmpeg
  - pip
  - pip:
      - faster-whisper
      - transformers
      - huggingface_hub
      - accelerate
      - flask
      - scikit-image
      - notebook
      - ipywidgets
